In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np


In [ ]:
set1={"aman","222",777,400.4}
x=tuple(set1)
print (x)

(400.4, 777, 'aman', '222')


In [ ]:
dict={"roll_no":20235,"name":"rishi","last_name:":"kunnath","date_of_birth":"10.08.2002"}
print(dict)

{'roll_no': 20235, 'name': 'rishi', 'last_name:': 'kunnath', 'date_of_birth': '10.08.2002'}


In [ ]:
import random as rand


In [ ]:
np.random.randint(4,size=(4,5))
#np.random is a module---rand is a function in that

array([[3, 3, 0, 2, 0],
       [1, 1, 3, 3, 1],
       [2, 3, 2, 1, 2],
       [2, 3, 1, 3, 3]])

In [ ]:
np.random.rand(1)



array([0.31583794])

In [ ]:
x=-1234
np.absolute(x)

1234

In [ ]:
np.random.randint(20,90)

57

In [ ]:
set1={11,12,13,14,15}
a=[]
for i in range(len(set1)):
  a.append(i)
print(a)
print(set1)
np.random.choice(set1)

[0, 1, 2, 3, 4]
{11, 12, 13, 14, 15}


ValueError: ignored

In [ ]:
file1=open("myfile.txt","w")

In [ ]:
file1.write("The King is Dead, Long Live The King")
file1.close()

In [ ]:
file1=open("myfile.txt","r")
print(file1.read())

The King is Dead, Long Live The King


In [ ]:
file1.close()


In [ ]:
def functions(a,b,c):
  if a>b:
    if a>c:
      print(a)
  elif b>c:
      print (b)

  else:
      print(c)
functions(10,20,30)
  

30


In [ ]:
def loops():
  i=0
  while(i<5):
    print(i)
    if(i==1):
      continue
    else:
      break
loops()


0


In [ ]:
string="    The King is Dead, Long Live The King      "
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
print(string.split())
print(string.strip())

    The King is Dead, Long Live The King      
 
 Th
 The King is Dead, Long Live The King      
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']
The King is Dead, Long Live The King


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x)

[[1 2 3]
 [4 5 6]]


In [ ]:
list1=[1,2,4,5,8]
x=np.array(list1)
print(x[:2])


[1 2]


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
print(x[1:])

[[4 5 6]]


In [ ]:
x=np.array([[1,2,3],[4,5,6]])
y=x.reshape(-1)
print(y)
print(y.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
array=[1,2,3]
sum=0
for i in range(len(array)):
  sum=sum+array[i]
print(sum)

6


In [ ]:

array=[77,74,75]
pro=1
for i in range(len(array)):
  pro=pro*array[i]
print(pro)

427350


In [ ]:
arr1=[1,2,3]
arr2=[4,5,6]
pro=0
for i in range(len(arr1)):
  for j in range(len(arr2)):
    if i==j:
      pro=pro+arr1[i]*arr2[j]
print(pro)
  
    

32


In [ ]:
arr=[1,1,4,5,5,5,7]
arr1=[]
for i in range(len(arr)):
  if arr[i] not in arr1:
    arr1.append(arr[i])
print(arr1)

[1, 4, 5, 7]


In [ ]:
list1=[1,2,3]
arr=np.array(list1)
print(arr)

[1 2 3]


In [ ]:
arr=np.array([1,2,3])
arr.fill(9)
print(arr)

[9 9 9]


In [ ]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr1.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.argmin(arr))



12.461538461538462
19.165736192147232
367.32544378698225
56
1
2.0
12
1


In [ ]:
arr=np.array([[2,-12],[1,-5]])
x,y=np.linalg.eig(arr)
print(x)
print(y)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]


In [ ]:
arr=np.array([[11, 22, 11, 31],[25, 33, 31, 28]])
result = np.corrcoef(arr)

print(result)


[[1.         0.15997968]
 [0.15997968 1.        ]]
